"""empty message

Revision ID: 28b653d3d0ac
Revises: 2651a4f38568
Create Date: 2023-07-12 00:41:42.201980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b653d3d0ac'
down_revision = '2651a4f38568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('planets_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['People.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['Planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Favoritos')
    # ### end Alembic commands ###
